// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/auth/auth.proto

package authSrvPb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Source int32

const (
	Source_PC      Source = 0
	Source_H5      Source = 1
	Source_ANDROID Source = 2
	Source_IOS     Source = 3
	Source_WX      Source = 4
	Source_ALL     Source = 100
)

var Source_name = map[int32]string{
	0:   "PC",
	1:   "H5",
	2:   "ANDROID",
	3:   "IOS",
	4:   "WX",
	100: "ALL",
}

var Source_value = map[string]int32{
	"PC":      0,
	"H5":      1,
	"ANDROID": 2,
	"IOS":     3,
	"WX":      4,
	"ALL":     100,
}

func (x Source) String() string {
	return proto.EnumName(Source_name, int32(x))
}

func (Source) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{0}
}

type Role int32

const (
	Role_USER  Role = 0
	Role_ADMIN Role = 1
)

var Role_name = map[int32]string{
	0: "USER",
	1: "ADMIN",
}

var Role_value = map[string]int32{
	"USER":  0,
	"ADMIN": 1,
}

func (x Role) String() string {
	return proto.EnumName(Role_name, int32(x))
}

func (Role) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{1}
}

type BaseRsp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseRsp) Reset()         { *m = BaseRsp{} }
func (m *BaseRsp) String() string { return proto.CompactTextString(m) }
func (*BaseRsp) ProtoMessage()    {}
func (*BaseRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{0}
}

func (m *BaseRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseRsp.Unmarshal(m, b)
}
func (m *BaseRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseRsp.Marshal(b, m, deterministic)
}
func (m *BaseRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseRsp.Merge(m, src)
}
func (m *BaseRsp) XXX_Size() int {
	return xxx_messageInfo_BaseRsp.Size(m)
}
func (m *BaseRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseRsp.DiscardUnknown(m)
}

var xxx_messageInfo_BaseRsp proto.InternalMessageInfo

type MakeTokenReq struct {
	Token                *Token   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MakeTokenReq) Reset()         { *m = MakeTokenReq{} }
func (m *MakeTokenReq) String() string { return proto.CompactTextString(m) }
func (*MakeTokenReq) ProtoMessage()    {}
func (*MakeTokenReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{1}
}

func (m *MakeTokenReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MakeTokenReq.Unmarshal(m, b)
}
func (m *MakeTokenReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MakeTokenReq.Marshal(b, m, deterministic)
}
func (m *MakeTokenReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MakeTokenReq.Merge(m, src)
}
func (m *MakeTokenReq) XXX_Size() int {
	return xxx_messageInfo_MakeTokenReq.Size(m)
}
func (m *MakeTokenReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MakeTokenReq.DiscardUnknown(m)
}

var xxx_messageInfo_MakeTokenReq proto.InternalMessageInfo

func (m *MakeTokenReq) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

type MakeTokenResp struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MakeTokenResp) Reset()         { *m = MakeTokenResp{} }
func (m *MakeTokenResp) String() string { return proto.CompactTextString(m) }
func (*MakeTokenResp) ProtoMessage()    {}
func (*MakeTokenResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{2}
}

func (m *MakeTokenResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MakeTokenResp.Unmarshal(m, b)
}
func (m *MakeTokenResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MakeTokenResp.Marshal(b, m, deterministic)
}
func (m *MakeTokenResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MakeTokenResp.Merge(m, src)
}
func (m *MakeTokenResp) XXX_Size() int {
	return xxx_messageInfo_MakeTokenResp.Size(m)
}
func (m *MakeTokenResp) XXX_DiscardUnknown() {
	xxx_messageInfo_MakeTokenResp.DiscardUnknown(m)
}

var xxx_messageInfo_MakeTokenResp proto.InternalMessageInfo

func (m *MakeTokenResp) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type CheckTokenReq struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckTokenReq) Reset()         { *m = CheckTokenReq{} }
func (m *CheckTokenReq) String() string { return proto.CompactTextString(m) }
func (*CheckTokenReq) ProtoMessage()    {}
func (*CheckTokenReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{3}
}

func (m *CheckTokenReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckTokenReq.Unmarshal(m, b)
}
func (m *CheckTokenReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckTokenReq.Marshal(b, m, deterministic)
}
func (m *CheckTokenReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckTokenReq.Merge(m, src)
}
func (m *CheckTokenReq) XXX_Size() int {
	return xxx_messageInfo_CheckTokenReq.Size(m)
}
func (m *CheckTokenReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckTokenReq.DiscardUnknown(m)
}

var xxx_messageInfo_CheckTokenReq proto.InternalMessageInfo

func (m *CheckTokenReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type CheckTokenResp struct {
	Token                *Token   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckTokenResp) Reset()         { *m = CheckTokenResp{} }
func (m *CheckTokenResp) String() string { return proto.CompactTextString(m) }
func (*CheckTokenResp) ProtoMessage()    {}
func (*CheckTokenResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{4}
}

func (m *CheckTokenResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckTokenResp.Unmarshal(m, b)
}
func (m *CheckTokenResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckTokenResp.Marshal(b, m, deterministic)
}
func (m *CheckTokenResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckTokenResp.Merge(m, src)
}
func (m *CheckTokenResp) XXX_Size() int {
	return xxx_messageInfo_CheckTokenResp.Size(m)
}
func (m *CheckTokenResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckTokenResp.DiscardUnknown(m)
}

var xxx_messageInfo_CheckTokenResp proto.InternalMessageInfo

func (m *CheckTokenResp) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

type DelTokenReq struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelTokenReq) Reset()         { *m = DelTokenReq{} }
func (m *DelTokenReq) String() string { return proto.CompactTextString(m) }
func (*DelTokenReq) ProtoMessage()    {}
func (*DelTokenReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{5}
}

func (m *DelTokenReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelTokenReq.Unmarshal(m, b)
}
func (m *DelTokenReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelTokenReq.Marshal(b, m, deterministic)
}
func (m *DelTokenReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelTokenReq.Merge(m, src)
}
func (m *DelTokenReq) XXX_Size() int {
	return xxx_messageInfo_DelTokenReq.Size(m)
}
func (m *DelTokenReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DelTokenReq.DiscardUnknown(m)
}

var xxx_messageInfo_DelTokenReq proto.InternalMessageInfo

func (m *DelTokenReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type Token struct {
	Source               Source   `protobuf:"varint,1,opt,name=source,proto3,enum=dsvo.auth.srv.Source" json:"source,omitempty"`
	Ip                   string   `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Mk                   string   `protobuf:"bytes,3,opt,name=mk,proto3" json:"mk,omitempty"`
	Uin                  int32    `protobuf:"varint,4,opt,name=uin,proto3" json:"uin,omitempty"`
	Role                 Role     `protobuf:"varint,5,opt,name=role,proto3,enum=dsvo.auth.srv.Role" json:"role,omitempty"`
	Skey                 string   `protobuf:"bytes,6,opt,name=skey,proto3" json:"skey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{6}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetSource() Source {
	if m != nil {
		return m.Source
	}
	return Source_PC
}

func (m *Token) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *Token) GetMk() string {
	if m != nil {
		return m.Mk
	}
	return ""
}

func (m *Token) GetUin() int32 {
	if m != nil {
		return m.Uin
	}
	return 0
}

func (m *Token) GetRole() Role {
	if m != nil {
		return m.Role
	}
	return Role_USER
}

func (m *Token) GetSkey() string {
	if m != nil {
		return m.Skey
	}
	return ""
}

func init() {
	proto.RegisterEnum("dsvo.auth.srv.Source", Source_name, Source_value)
	proto.RegisterEnum("dsvo.auth.srv.Role", Role_name, Role_value)
	proto.RegisterType((*BaseRsp)(nil), "dsvo.auth.srv.BaseRsp")
	proto.RegisterType((*MakeTokenReq)(nil), "dsvo.auth.srv.MakeTokenReq")
	proto.RegisterType((*MakeTokenResp)(nil), "dsvo.auth.srv.MakeTokenResp")
	proto.RegisterType((*CheckTokenReq)(nil), "dsvo.auth.srv.CheckTokenReq")
	proto.RegisterType((*CheckTokenResp)(nil), "dsvo.auth.srv.CheckTokenResp")
	proto.RegisterType((*DelTokenReq)(nil), "dsvo.auth.srv.DelTokenReq")
	proto.RegisterType((*Token)(nil), "dsvo.auth.srv.Token")
}

func init() {
	proto.RegisterFile("proto/auth/auth.proto", fileDescriptor_82b5829f48cfb8e5)
}

var fileDescriptor_82b5829f48cfb8e5 = []byte{
	// 407 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0x6d, 0x8b, 0xd3, 0x40,
	0x10, 0xc7, 0xf3, 0xdc, 0xcb, 0xc4, 0x2b, 0xcb, 0x78, 0x27, 0x21, 0xa7, 0x70, 0x44, 0xc4, 0xa3,
	0x60, 0x84, 0x8a, 0x6f, 0x44, 0xd0, 0xdc, 0x45, 0xb8, 0xe2, 0x5d, 0x5b, 0x36, 0x8a, 0xe2, 0xbb,
	0x3e, 0x2c, 0x34, 0xa4, 0x6d, 0x62, 0x36, 0x09, 0xf8, 0x81, 0xfc, 0x6a, 0x7e, 0x0e, 0xd9, 0x8d,
	0xad, 0x69, 0xf0, 0x81, 0x7b, 0x93, 0xcc, 0xc3, 0x6f, 0xfe, 0x33, 0x30, 0xb3, 0x70, 0x9a, 0x17,
	0x59, 0x99, 0x3d, 0x9f, 0x55, 0xe5, 0x4a, 0x7e, 0x02, 0xe9, 0xe3, 0xf1, 0x92, 0xd7, 0x59, 0x20,
	0x03, 0xbc, 0xa8, 0x7d, 0x1b, 0x7a, 0x97, 0x33, 0xce, 0x28, 0xcf, 0xfd, 0x57, 0x70, 0xef, 0x76,
	0x96, 0xb2, 0x0f, 0x59, 0xca, 0xb6, 0x94, 0x7d, 0xc5, 0x01, 0x98, 0xa5, 0xb0, 0x5d, 0xf5, 0x5c,
	0xbd, 0x70, 0x86, 0x27, 0xc1, 0x41, 0x65, 0xd0, 0x70, 0x0d, 0xe2, 0x3f, 0x81, 0xe3, 0x56, 0x2d,
	0xcf, 0xf1, 0xa4, 0x5d, 0x6c, 0xb7, 0xb0, 0xab, 0x15, 0x5b, 0xa4, 0xfb, 0x1e, 0x7f, 0xc6, 0x5e,
	0x43, 0xbf, 0x8d, 0xf1, 0xfc, 0x4e, 0xb3, 0x3c, 0x06, 0x27, 0x62, 0xeb, 0xff, 0xb4, 0xf8, 0xae,
	0x82, 0x29, 0x11, 0x7c, 0x06, 0x16, 0xcf, 0xaa, 0x62, 0xc1, 0x24, 0xd0, 0x1f, 0x9e, 0x76, 0xb4,
	0x63, 0x99, 0xa4, 0xbf, 0x20, 0xec, 0x83, 0x96, 0xe4, 0xae, 0x26, 0xb5, 0xb4, 0x24, 0x17, 0xfe,
	0x26, 0x75, 0xf5, 0xc6, 0xdf, 0xa4, 0x48, 0x40, 0xaf, 0x92, 0xad, 0x6b, 0x9c, 0xab, 0x17, 0x26,
	0x15, 0x26, 0x3e, 0x05, 0xa3, 0xc8, 0xd6, 0xcc, 0x35, 0xa5, 0xfc, 0xfd, 0x8e, 0x3c, 0xcd, 0xd6,
	0x8c, 0x4a, 0x00, 0x11, 0x0c, 0x9e, 0xb2, 0x6f, 0xae, 0x25, 0xc5, 0xa4, 0x3d, 0x78, 0x03, 0x56,
	0x33, 0x00, 0x5a, 0xa0, 0x4d, 0xaf, 0x88, 0x22, 0xfe, 0xd7, 0x2f, 0x89, 0x8a, 0x0e, 0xf4, 0xc2,
	0x71, 0x44, 0x27, 0xa3, 0x88, 0x68, 0xd8, 0x03, 0x7d, 0x34, 0x89, 0x89, 0x2e, 0xb2, 0x9f, 0x3e,
	0x13, 0x43, 0x04, 0xc2, 0x9b, 0x1b, 0xb2, 0x1c, 0x9c, 0x81, 0x21, 0x5a, 0xe0, 0x11, 0x18, 0x1f,
	0xe3, 0x77, 0x94, 0x28, 0x68, 0x83, 0x19, 0x46, 0xb7, 0xa3, 0x31, 0x51, 0x87, 0x3f, 0x54, 0x70,
	0xc2, 0xaa, 0x5c, 0xc5, 0xac, 0xa8, 0x93, 0x05, 0xc3, 0x6b, 0xb0, 0xf7, 0x6b, 0xc4, 0xb3, 0xce,
	0xa4, 0xed, 0xe3, 0xf0, 0x1e, 0xfe, 0x3d, 0xc9, 0x73, 0x5f, 0xc1, 0xf7, 0x00, 0xbf, 0x57, 0x88,
	0x5d, 0xfa, 0xe0, 0x08, 0xbc, 0x47, 0xff, 0xc8, 0x4a, 0xb1, 0xb7, 0x70, 0xb4, 0xdb, 0x28, 0x7a,
	0x1d, 0xb8, 0xb5, 0x6a, 0xef, 0x41, 0x27, 0xb7, 0xbb, 0x6c, 0xe5, 0xd2, 0xf9, 0x62, 0x8b, 0x68,
	0x5c, 0xd4, 0xd3, 0xf9, 0xdc, 0x92, 0x2f, 0xe1, 0xc5, 0xcf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1e,
	0xe6, 0xd3, 0x26, 0x22, 0x03, 0x00, 0x00,
}
